here::i_am("R/histogram2.R")
movies <- read.csv(here::here('data','movies.csv'),stringsAsFactors=FALSE)
ratings <- read.csv(here::here('data',"ratings.csv"))
movie_rating <- merge(ratings,movies,by="movieId")
library(readr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(scales)
library(dplyr)
png(file= here::here('figs','hist2.png'))
rating_dist <- movie_rating %>% group_by(rating) %>% summarize(n=n())
ggplot(rating_dist, aes(x=rating, y=n))+geom_col()+labs(title="Ratings Distribution", y="Count",x="Ratings")
dev.off()